### ISSUE TITLE
Comment Syntax

### ISSUE THREAD

**Issue by s0kil** [faustinoaq/vscode-mint-lang#2]
Vscode sets comment to `#` but Mint lang comment is `/* */`.

**Comment by faustinoaq** [comment]
I'm fixing this, Thanks for report it :+1:

**Comment by s0kil** [comment]
@faustinoaq Could you also update to support latest Mint features, like `enum`?

**Comment by faustinoaq** [comment]
@DanielSokil Yeah, I'll do :+1:

**Comment by mationai** [comment]
@faustinoaq It would be great if the comment syntax can be fixed. I tried looking at https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json for inspiration, but it seems a bit over my head.

**Comment by s0kil** [comment]
@fuzzthink Comment Syntax Is Now Supported In This Fork: https://github.com/s0kil/mint-vscode
